#ifndef PACKET_H
#define PACKET_H


#define PACKET_SIZE 256
#define PACKET_STATUS_POS 0
#define PACKET_INST_POS 0
#define PACKET_DATA_START 1



#define FRAME_START_MAGIC 0xCEC4
#define FRAME_END_MAGIC 0x0F14
#define FRAME_SIZE PACKET_SIZE + 4




enum PACKET_INSTRUCTION_TYPE {
  PROG_ENABLE,
  CHIP_ERASE,
  WRITE_FLASH,
  READ_FLASH,
  WRITE_EEPROM,
  READ_EEPROM,
  WRITE_FUSE,
  READ_FUSE
};

enum PACKET_ERROR_STATUS {OK, MALFORMED_PACKET, EXEC_ERR};

#endif
